package com.mycompany.os_project;

import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author melha
 */
public class Project_GUI extends javax.swing.JFrame {
     Queue<PCB> Processes = new LinkedList<>();
     Queue<PCB> RRProcesses = new LinkedList<>();
     Queue<PCB> SJFProcesses = new LinkedList<>();
     RoundRobinScheduler Sch1 = new RoundRobinScheduler();
     SjfScheduler Sch2 = new SjfScheduler();
     
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Project_GUI.class.getName());
    
    /**
     * Creates new form Project_GUI
     */
    public Project_GUI() {
        initComponents();
        jTextArea1.setEditable(false); 
    jTextArea1.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
    jTextArea2.setEditable(false); 
    jTextArea2.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
    
    DefaultTableModel model2 = (DefaultTableModel) RRTable.getModel();
    model2.setRowCount(0); 
    DefaultTableModel model3 = (DefaultTableModel) SJFTable.getModel();
    model3.setRowCount(0); 
    }

       
    
private String getFinalConclusion(Queue<PCB> sjfRes, Queue<PCB> rrRes) {

    double sjfWT = Sch2.AverageWaitingTime(SJFProcesses); 
    double rrWT = Sch1.AverageWaitingTime(RRProcesses);
    
    double sjfRT = Sch2.AverageRT(SJFProcesses);
    double rrRT = Sch1.AverageRT(RRProcesses);
    
    double sjfTAT = Sch2.AverageTAT(SJFProcesses);
    double rrTAT = Sch1.AverageTAT(RRProcesses);


    StringBuilder conclusion = new StringBuilder();
    
    if (sjfWT <= rrWT) {
        conclusion.append(" SJF is more efficient in Waiting Time.\n");}
     else {
        conclusion.append(" Round Robin is more efficient in Waiting Time.\n");}
    
    if (sjfTAT <= rrTAT) {
        conclusion.append(" SJF provides better TurnAround Time.\n");}
     else {
        conclusion.append(" Round Robin provides better TurnAround Time.\n");}
    
    if (sjfRT <= rrRT) {
        conclusion.append(" SJF provides better Response Time.\n");}
     else {
        conclusion.append(" Round Robin provides better Response Time.\n");}
    conclusion.append("Conclusion:\n");
    if (sjfWT <= rrWT){ conclusion.append(" SJF is the better algorithm here if we value effeciency more\n");
            }else{conclusion.append(" RR is the better algorithm here if we value effeciency more\n");}
    if (sjfRT <= rrRT){ conclusion.append(" SJF is the better algorithm here if we value Respose more\n");
            }else{conclusion.append(" RR is the better algorithm here if we value Fairness more\n");}
    return conclusion.toString();
}
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProcess = new javax.swing.JTable();
        jButtonAddProcess = new javax.swing.JButton();
        LablePID = new javax.swing.JLabel();
        LableAT = new javax.swing.JLabel();
        LableBT = new javax.swing.JLabel();
        LableRR = new javax.swing.JLabel();
        TextFieldPID = new javax.swing.JTextField();
        TextFieldAT = new javax.swing.JTextField();
        TextFieldBT = new javax.swing.JTextField();
        TextFieldQuantum = new javax.swing.JTextField();
        ButtonAddProcess = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        ButtonReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        RRTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        SJFTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        comparisonTextFeild = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jTableProcess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "Arrival", "Burst"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProcess.getTableHeader().setReorderingAllowed(false);
        jTableProcess.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTableProcessInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProcess);

        jButtonAddProcess.setText("Excute");
        jButtonAddProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProcessActionPerformed(evt);
            }
        });

        LablePID.setText("PID");

        LableAT.setText("Arrival Time");

        LableBT.setText("Burst Time");

        LableRR.setText("Quantum(RR)");

        TextFieldPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPIDActionPerformed(evt);
            }
        });

        TextFieldAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldATActionPerformed(evt);
            }
        });

        TextFieldQuantum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldQuantumActionPerformed(evt);
            }
        });

        ButtonAddProcess.setText("Add Process");
        ButtonAddProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddProcessActionPerformed(evt);
            }
        });

        ButtonDelete.setText("Delete");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ButtonReset.setText("Reset");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jLabel1.setText("SJF Output");

        jLabel2.setText("Round Robin Excuted Proceses");

        RRTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "PID", "AT", "BT", "CT", "TAT", "RT"
            }
        ));
        jScrollPane4.setViewportView(RRTable);

        SJFTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "PID", "AT", "BT", "CT", "TAT", "RT"
            }
        ));
        jScrollPane5.setViewportView(SJFTable);

        jLabel3.setText("SJF Excuted Proceses");

        jLabel4.setText("Round Robin Output");

        comparisonTextFeild.setEditable(false);
        comparisonTextFeild.setColumns(20);
        comparisonTextFeild.setLineWrap(true);
        comparisonTextFeild.setRows(5);
        jScrollPane6.setViewportView(comparisonTextFeild);

        jLabel5.setText("Comparison Summary");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LablePID)
                            .addComponent(TextFieldPID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldAT, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LableAT))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldBT, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LableBT, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(ButtonAddProcess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonDelete)
                        .addGap(76, 76, 76)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonReset)
                        .addGap(113, 113, 113)
                        .addComponent(jButtonAddProcess)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextFieldQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(LableRR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(693, 693, 693))
                            .addComponent(jScrollPane3))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(214, 214, 214))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LablePID)
                    .addComponent(LableAT)
                    .addComponent(LableBT)
                    .addComponent(LableRR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAddProcess)
                    .addComponent(ButtonDelete)
                    .addComponent(ButtonReset)
                    .addComponent(jButtonAddProcess))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProcessActionPerformed
         
            DefaultTableModel model5 = (DefaultTableModel) RRTable.getModel();
        model5.setRowCount(0); 
        DefaultTableModel model6 = (DefaultTableModel) SJFTable.getModel();
        model6.setRowCount(0); 
        DefaultTableModel model = (DefaultTableModel) jTableProcess.getModel();

      
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Error: No processes in the table!");
            return;
        }
        
        Processes.clear();
        for (int i = 0; i < model.getRowCount(); i++) {
            Processes.add(new PCB(
                Integer.parseInt(model.getValueAt(i, 0).toString()),
                Double.parseDouble(model.getValueAt(i, 1).toString()),
                Double.parseDouble(model.getValueAt(i, 2).toString())
            ));
        }

        
        String quantumStr = TextFieldQuantum.getText().trim();

        if (quantumStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a quantum value!");
            return;
        }
        

        try {
            int quantum = Integer.parseInt(quantumStr);

            if (quantum <= 0) {
                JOptionPane.showMessageDialog(this, "Quantum must be a positive integer greater than 0!");
                return;
            }

            Sch1.setQuantum(quantum);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input: Quantum must be a number.");
            return;
        }
        
    String RR_Output =  Sch1.execute(Processes,RRProcesses)+"\n";
    String SJF_Output =  Sch2.execute(Processes,SJFProcesses)+"\n";
    jTextArea2.setText(RR_Output);
    jTextArea1.setText(SJF_Output);
    
    String finalResult = getFinalConclusion(SJFProcesses, RRProcesses);
    comparisonTextFeild.setText(finalResult);
    
      DefaultTableModel model2 = (DefaultTableModel) RRTable.getModel();
           
           for (PCB p: RRProcesses){
                model2.addRow(new Object[]{
                p.PID, 
                p.AT,  
                p.BT, 
                p.CT,       
                p.TAT,       
                p.RT         
            });
           } 
           DefaultTableModel model3 = (DefaultTableModel) SJFTable.getModel();
           
           for (PCB p: SJFProcesses){
                model3.addRow(new Object[]{
                p.PID, 
                p.AT,  
                p.BT, 
                p.CT,       
                p.TAT,       
                p.RT         
            });
           } 

    }//GEN-LAST:event_jButtonAddProcessActionPerformed

    private void TextFieldPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPIDActionPerformed
        
    }//GEN-LAST:event_TextFieldPIDActionPerformed

    private void TextFieldATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldATActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableProcess.getModel();
        int selectedRow = jTableProcess.getSelectedRow();

        if(selectedRow != -1) { 
            model.removeRow(selectedRow);
        } else {
            if(model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is already empty.");
            } else {
                JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        }
    }
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonAddProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddProcessActionPerformed
        String pidStr = TextFieldPID.getText().trim();
        String atStr = TextFieldAT.getText().trim();
        String btStr = TextFieldBT.getText().trim();
       
        if(pidStr.isEmpty() || atStr.isEmpty() || btStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: Missing required fields!");
            return; 
        }

        try {
            int at = Integer.parseInt(atStr);
            int bt = Integer.parseInt(btStr);
            int pid = Integer.parseInt(pidStr);
            if (at < 0) {
                JOptionPane.showMessageDialog(this, "Arrival Time cannot be negative!");
                return;
            }
            if (bt <= 0) {
                JOptionPane.showMessageDialog(this, "Burst Time must be greater than 0!");
                return;
            }
             
            
            
            DefaultTableModel model = (DefaultTableModel) jTableProcess.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                if (model.getValueAt(i, 0).toString().equals(pidStr)) {
                    JOptionPane.showMessageDialog(this, "Duplicate Process ID detected!");
                    return;
                }
            }
            
            model.addRow(new Object[]{pidStr, at, bt});

           
            
            TextFieldPID.setText("");
            TextFieldAT.setText("");
            TextFieldBT.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input: Please enter numeric values for Time fields.");
        }
    }//GEN-LAST:event_ButtonAddProcessActionPerformed

    private void jTableProcessInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTableProcessInputMethodTextChanged
       
    }//GEN-LAST:event_jTableProcessInputMethodTextChanged

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
    TextFieldPID.setText("");
    TextFieldAT.setText("");
    TextFieldBT.setText("");
    TextFieldQuantum.setText("");
    jTextArea1.setText("");
    jTextArea2.setText("");
    comparisonTextFeild.setText("");
   
    DefaultTableModel model = (DefaultTableModel) jTableProcess.getModel();
    model.setRowCount(0);        // TODO add your handling code here:
    DefaultTableModel model2 = (DefaultTableModel) RRTable.getModel();
    model2.setRowCount(0); 
    DefaultTableModel model3 = (DefaultTableModel) SJFTable.getModel();
    model3.setRowCount(0); 
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void TextFieldQuantumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldQuantumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldQuantumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Project_GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddProcess;
    public javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JLabel LableAT;
    private javax.swing.JLabel LableBT;
    private javax.swing.JLabel LablePID;
    private javax.swing.JLabel LableRR;
    private javax.swing.JTable RRTable;
    private javax.swing.JTable SJFTable;
    private javax.swing.JTextField TextFieldAT;
    private javax.swing.JTextField TextFieldBT;
    private javax.swing.JTextField TextFieldPID;
    private javax.swing.JTextField TextFieldQuantum;
    private javax.swing.JTextArea comparisonTextFeild;
    private javax.swing.JButton jButtonAddProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableProcess;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
