package com.mycompany.os_project;

import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author melha
 */
public class Project_GUI extends javax.swing.JFrame {
     Queue<PCB> Processes = new LinkedList<>();
     RoundRobinScheduler Sch1 = new RoundRobinScheduler();
     SjfScheduler Sch2 = new SjfScheduler();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Project_GUI.class.getName());
    
    /**
     * Creates new form Project_GUI
     */
    public Project_GUI() {
        initComponents();
        jTextArea1.setEditable(false); 
    jTextArea1.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
    jTextArea2.setEditable(false); 
    jTextArea2.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProcess = new javax.swing.JTable();
        jButtonAddProcess = new javax.swing.JButton();
        LablePID = new javax.swing.JLabel();
        LableAT = new javax.swing.JLabel();
        LableBT = new javax.swing.JLabel();
        LableRR = new javax.swing.JLabel();
        TextFieldPID = new javax.swing.JTextField();
        TextFieldAT = new javax.swing.JTextField();
        TextFieldBT = new javax.swing.JTextField();
        TextFieldQuantum = new javax.swing.JTextField();
        ButtonAddProcess = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        ButtonReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableProcess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "Arrival", "Burst"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProcess.getTableHeader().setReorderingAllowed(false);
        jTableProcess.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTableProcessInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProcess);

        jButtonAddProcess.setText("Excute");
        jButtonAddProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProcessActionPerformed(evt);
            }
        });

        LablePID.setText("PID");

        LableAT.setText("Arrival Time");

        LableBT.setText("Burst Time");

        LableRR.setText("Quantum(RR)");

        TextFieldPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPIDActionPerformed(evt);
            }
        });

        TextFieldAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldATActionPerformed(evt);
            }
        });

        TextFieldQuantum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldQuantumActionPerformed(evt);
            }
        });

        ButtonAddProcess.setText("Add Process");
        ButtonAddProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddProcessActionPerformed(evt);
            }
        });

        ButtonDelete.setText("Delete");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ButtonReset.setText("Reset");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("SJF Output");
        jScrollPane2.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Round Robin Output");
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LablePID)
                            .addComponent(TextFieldPID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LableAT)
                            .addComponent(TextFieldAT, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LableBT, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldBT, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(ButtonAddProcess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonDelete)
                        .addGap(76, 76, 76)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LableRR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonReset)
                            .addComponent(TextFieldQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 133, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jButtonAddProcess)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LablePID)
                    .addComponent(LableAT)
                    .addComponent(LableBT)
                    .addComponent(LableRR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAddProcess)
                    .addComponent(ButtonDelete)
                    .addComponent(ButtonReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddProcess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProcessActionPerformed
         DefaultTableModel model = (DefaultTableModel) jTableProcess.getModel();

      
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Error: No processes in the table!");
            return;
        }
        
        Processes.clear();
        for (int i = 0; i < model.getRowCount(); i++) {
            Processes.add(new PCB(
                Integer.parseInt(model.getValueAt(i, 0).toString()),
                Double.parseDouble(model.getValueAt(i, 1).toString()),
                Double.parseDouble(model.getValueAt(i, 2).toString())
            ));
        }

        
        String quantumStr = TextFieldQuantum.getText().trim();

        if (quantumStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a quantum value!");
            return;
        }
        

        try {
            int quantum = Integer.parseInt(quantumStr);

            if (quantum <= 0) {
                JOptionPane.showMessageDialog(this, "Quantum must be a positive integer greater than 0!");
                return;
            }

            Sch1.setQuantum(quantum);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input: Quantum must be a number.");
            return;
        }
        
    String RR_Output = "Round Robin Output\n";
    RR_Output +=  Sch1.execute(Processes)+"\n";
    String SJF_Output = "SJF Output\n";
    SJF_Output +=  Sch2.execute(Processes)+"\n";
    jTextArea1.setText(RR_Output);
    jTextArea2.setText(SJF_Output);

    }//GEN-LAST:event_jButtonAddProcessActionPerformed

    private void TextFieldPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPIDActionPerformed
        
    }//GEN-LAST:event_TextFieldPIDActionPerformed

    private void TextFieldATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldATActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableProcess.getModel();
        int selectedRow = jTableProcess.getSelectedRow();

        if(selectedRow != -1) { 
            model.removeRow(selectedRow);
        } else {
            if(model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is already empty.");
            } else {
                JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        }
    }
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonAddProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddProcessActionPerformed
        String pidStr = TextFieldPID.getText().trim();
        String atStr = TextFieldAT.getText().trim();
        String btStr = TextFieldBT.getText().trim();
       
        if(pidStr.isEmpty() || atStr.isEmpty() || btStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: Missing required fields!");
            return; 
        }

        try {
            int at = Integer.parseInt(atStr);
            int bt = Integer.parseInt(btStr);
        
            if (at < 0) {
                JOptionPane.showMessageDialog(this, "Arrival Time cannot be negative!");
                return;
            }
            if (bt <= 0) {
                JOptionPane.showMessageDialog(this, "Burst Time must be greater than 0!");
                return;
            }

        
            DefaultTableModel model = (DefaultTableModel) jTableProcess.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                if (model.getValueAt(i, 0).toString().equals(pidStr)) {
                    JOptionPane.showMessageDialog(this, "Duplicate Process ID detected!");
                    return;
                }
            }
            
            model.addRow(new Object[]{pidStr, at, bt});

           
            
            TextFieldPID.setText("");
            TextFieldAT.setText("");
            TextFieldBT.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input: Please enter numeric values for Time fields.");
        }
    }//GEN-LAST:event_ButtonAddProcessActionPerformed

    private void jTableProcessInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTableProcessInputMethodTextChanged
       
    }//GEN-LAST:event_jTableProcessInputMethodTextChanged

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
    TextFieldPID.setText("");
    TextFieldAT.setText("");
    TextFieldBT.setText("");
    TextFieldQuantum.setText("");
    
    
    jTextArea1.setText("SJF Output :");
    jTextArea2.setText("Round Robin Output :");
    
   
    DefaultTableModel model = (DefaultTableModel) jTableProcess.getModel();
    model.setRowCount(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void TextFieldQuantumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldQuantumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldQuantumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Project_GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddProcess;
    public javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JLabel LableAT;
    private javax.swing.JLabel LableBT;
    private javax.swing.JLabel LablePID;
    private javax.swing.JLabel LableRR;
    private javax.swing.JTextField TextFieldAT;
    private javax.swing.JTextField TextFieldBT;
    private javax.swing.JTextField TextFieldPID;
    private javax.swing.JTextField TextFieldQuantum;
    private javax.swing.JButton jButtonAddProcess;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableProcess;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
