/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.os_project;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author melha
 */
public class Project_GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Project_GUI.class.getName());

    /**
     * Creates new form Project_GUI
     */
    public Project_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProcess = new javax.swing.JTable();
        jButtonAddProcess = new javax.swing.JButton();
        LablePID = new javax.swing.JLabel();
        LableAT = new javax.swing.JLabel();
        LableBT = new javax.swing.JLabel();
        LableRR = new javax.swing.JLabel();
        TextFieldPID = new javax.swing.JTextField();
        TextFieldAT = new javax.swing.JTextField();
        TextFieldBT = new javax.swing.JTextField();
        TextFieldRR = new javax.swing.JTextField();
        ButtonAddProcess = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        ButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableProcess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "Arrival", "Burst"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableProcess.getTableHeader().setReorderingAllowed(false);
        jTableProcess.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTableProcessInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProcess);

        jButtonAddProcess.setText("Excute");
        jButtonAddProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProcessActionPerformed(evt);
            }
        });

        LablePID.setText("PID");

        LableAT.setText("Arrival Time");

        LableBT.setText("Burst Time");

        LableRR.setText("Quantum(RR)");

        TextFieldPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPIDActionPerformed(evt);
            }
        });

        TextFieldAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldATActionPerformed(evt);
            }
        });

        ButtonAddProcess.setText("Add Process");
        ButtonAddProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddProcessActionPerformed(evt);
            }
        });

        ButtonDelete.setText("Delete");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ButtonReset.setText("Reset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(ButtonAddProcess)
                        .addGap(43, 43, 43)
                        .addComponent(ButtonDelete)
                        .addGap(43, 43, 43)
                        .addComponent(ButtonReset)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LablePID)
                            .addComponent(TextFieldPID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LableAT)
                            .addComponent(TextFieldAT, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LableBT, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldBT, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldRR, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LableRR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(15, 15, 15))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonAddProcess)
                                .addGap(196, 196, 196))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LablePID)
                    .addComponent(LableAT)
                    .addComponent(LableBT)
                    .addComponent(LableRR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldRR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAddProcess)
                    .addComponent(ButtonDelete)
                    .addComponent(ButtonReset))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddProcess)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProcessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddProcessActionPerformed

    private void TextFieldPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPIDActionPerformed

    private void TextFieldATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldATActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableProcess.getModel();
        int selectedRow = jTableProcess.getSelectedRow();

        if(selectedRow != -1) { 
            model.removeRow(selectedRow);
        } else {
            if(model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is already empty.");
            } else {
                JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        }
    }
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonAddProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddProcessActionPerformed
        String pid = TextFieldPID.getText().trim();
        String at = TextFieldAT.getText().trim();
        String bt = TextFieldBT.getText().trim();

        if(pid.isEmpty() || at.isEmpty() || bt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter All Data!");
            return; 
        }

        DefaultTableModel model = (DefaultTableModel) jTableProcess.getModel();
        model.addRow(new Object[]{pid, at, bt});
        
        TextFieldPID.setText("");
        TextFieldAT.setText("");
        TextFieldBT.setText("");
        TextFieldRR.setText("");
    }//GEN-LAST:event_ButtonAddProcessActionPerformed

    private void jTableProcessInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTableProcessInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableProcessInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Project_GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddProcess;
    public javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JLabel LableAT;
    private javax.swing.JLabel LableBT;
    private javax.swing.JLabel LablePID;
    private javax.swing.JLabel LableRR;
    private javax.swing.JTextField TextFieldAT;
    private javax.swing.JTextField TextFieldBT;
    private javax.swing.JTextField TextFieldPID;
    private javax.swing.JTextField TextFieldRR;
    private javax.swing.JButton jButtonAddProcess;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProcess;
    // End of variables declaration//GEN-END:variables
}
